[5] implementation add pill#4
QuadroiDev/Medic pull request #17
Opened 2023-12-07 15:47 UTC by mohammadjelodar13657

https://github.com/users/QuadroiDev/projects/6/views/1?pane=issue&itemId=45541455

2023-12-08 11:03 UTC, pooriadarvishi commented
java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: 062901eeda6397756b30e0210f40cf25, found: 9f9be63388712b975584953768dd10ae

با این ارور کرش میکنه برا من

2023-12-08 11:12 UTC, pooriadarvishi requested changes

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/res/drawable/pills.xml
> +    android:width="100dp"
اقا جلودار بهتره که برای این ایکون ها اول اسمشون یه ic_(name) بذاری (به جای name اسمشونو بنویس) کلا اینطوری قشنگ تره

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/core/model/converter/CategoryEntityToCategory.kt
> +
enter پاک شه please

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/core/model/converter/HabitEntityToHabit.kt
> +
این enter هم همینظور

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/data/local/ReminderLocalDataSource.kt
> +        habitDao.getAll().map { it.map { habitEntity -> habitEntityToHabit.map(habitEntity) } }
به جای این مپر به سه تا میپ میشه اینطوری ازش استفاده کرد 
همون مپر بیس ای که نوشتم 
![Uploading Screenshot 2023-12-08 at 1.16.47 PM.png…]()

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/data/local/ReminderLocalDataSource.kt
> +        habitDao.getAll().map { it.map { habitEntity -> habitEntityToHabit.map(habitEntity) } }
<img width="834" alt="Screenshot 2023-12-08 at 1 16 47 PM" src="https://github.com/QuadroiDev/Medic/assets/113296216/f2675a59-027e-461a-817a-aa8ee7cafa7a">

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/data/local/ReminderLocalDataSource.kt
> +    fun createReminder(habit: Habit) {
فکر میکنم اسم فانکشن ها مناسب نیست یعنی باید همه جا یکی باشه مثلا همه چا habit باشه یا reminder چه داخل دیتا سورس چه ریپازیتوری چ یوز کیس ها

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/data/local/ReminderLocalDataSource.kt
> +    fun createReminder(habit: Habit) {
<img width="1172" alt="Screenshot 2023-12-08 at 1 24 13 PM" src="https://github.com/QuadroiDev/Medic/assets/113296216/e7c48df0-2635-456e-b6a4-d4bdd3d773fc">
پرانتز این هم میتونه برداشته شه

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/domain/usecases/feature/createreminder/GetAllRemindersUseCase.kt
> +
enter اضافی ;)

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/domain/usecases/feature/createreminder/CreateReminderUseCase.kt
> +        Log.i("CreateReminderUseCase", "execute: ${params.habit.name}")
این لاگ رو فک کنم یادتون رفته بردارین

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/domain/usecases/feature/createreminder/GetAllRemindersUseCase.kt
> +class GetAllRemindersUseCase @Inject constructor(
برای این هم میشه ازون useCase که به عنوان base شناخته میشه استفاده کرد اگه نشد یا خوب نبود بگید باهم روش صحبت کنیم به یه جمع بندی برسیم که برای یه base پیاده سازی کنیم

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderViewModel.kt
> +    fun submitButtonClicked(
اسم این خیلی میتونه بهتر از این باشه ازین دید نگاهش کنید که ویو مدل هیچ اطلاعی از ویو نداره و دیدی نسبت به دکمه نداری میشه اسم ساخت عادت یا اضافه کردن عادت یا اسمای دیگه براش گذاشت که مفهومی ترن

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderViewModel.kt
> +class CreateReminderViewModel @Inject constructor(
اقا جلودار ببین میشه اسم بهتری براش پیدا کرد؟

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderViewModel.kt
> +    sealed class SubmitEvents {
اسم این با اسم ویو مدل یکی شه بهتره اسم چایلدهاش میتونه تغییر کنه

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/data/di/module/DataModule.kt
> +    fun provideReminderRepository(reminderLocalDataSource: ReminderLocalDataSource): ReminderRepository =
میشه به جای @provides چون یه ایمپلی از اینترفیس هست از @Binds استفاده کرد

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/main/MainAdapter.kt
> +class MainAdapter : ListAdapter<Habit, MainAdapter.MyViewHolder>(DIFF_UTIL) {
اسم این فک کنم pilladapter باشه بهتره 
<img width="966" alt="Screenshot 2023-12-08 at 2 22 23 PM" src="https://github.com/QuadroiDev/Medic/assets/113296216/12018c8c-f20b-4a98-bede-89a16ae3d3d1">
به جای ساخت ابجکت اینطوری میشه استفاده کرد که بهتره

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/main/MainAdapter.kt
> +                drugCountTextView.text = "${habit.count} pill(s) left"
این استرینگ بره داخل استرینگ ها خیلی بهتره
از string.format میتونی استفاده کنی

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/main/MainViewModel.kt
> +    private val _habits: Channel<List<Habit>> = Channel()
در مورد این باید باهم صحبت کنیم یادم بندازین لطفا :)

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/main/MainFragment.kt
> +            findNavController().navigate(R.id.action_mainFragment_to_createReminderFragment)
این باید بعد از event اتفاق بیوفته

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/main/MainFragment.kt
> +    private fun observeHabits() {
اسم این باید ابزرو ایونت باشه

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderFragment.kt
> +            categoryName = adapterView.getItemAtPosition(position).toString()
یه صحبت کلی باید در مورد این داشته باشیم این رو داخل لول های پایین تر ببریم

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderFragment.kt
> +            drugName = binding.drugNameEditText.text.toString()
این فقط همینجا استفاده داره نیاز به گلوبال کردنش نیشت

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderFragment.kt
> +        Log.e("Calendar", "$year, $month, $dayOfMonth")
در مورد این هم یه فایل داریم به اسم fileLog ازون میشه استفاده کرد

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderFragment.kt
> +        Log.i("Formatting", timeStamp.toString())
fileLog

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderFragment.kt
> +        binding.dateTextView.text = dateFormatter.format(timeStamp)
dateFormatter
این هم نیاز نیست گلوبال باشه

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderFragment.kt
> +        Log.i("Formatting", timeStamp.toString())
FilLog

2023-12-08 11:12 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/createreminder/CreateReminderFragment.kt
> +        binding.timeTextView.text = timeFormatter.format(timeStamp)
timeFormatter این هم نیاز نیست گلوبال باشه

2023-12-08 11:59 UTC, mohammadjelodar13657 commented on app/src/main/res/drawable/pills.xml
> +    android:width="100dp"
چشم نام ایکن ها اصلاح شد

2023-12-08 12:01 UTC, mohammadjelodar13657 commented on app/src/main/java/com/quadroidev/medic/core/model/converter/CategoryEntityToCategory.kt
> +
این و نمیفهمم باید چیکار کنم اگه میشه یا فارسی بنویس یا انگلیسی که متوجه بشم

2023-12-08 12:06 UTC, mohammadjelodar13657 commented on app/src/main/java/com/quadroidev/medic/core/model/converter/CategoryEntityToCategory.kt
> +
فهمیدم چی شد چشم اینتر های اضافی و حذف می کنم

2023-12-08 12:06 UTC, mohammadjelodar13657 commented on app/src/main/java/com/quadroidev/medic/core/model/converter/CategoryEntityToCategory.kt
> +
چشم همه اینتر های اضافی حذف میشن

2023-12-08 12:12 UTC, mohammadjelodar13657 commented on app/src/main/java/com/quadroidev/medic/data/local/ReminderLocalDataSource.kt
> +        habitDao.getAll().map { it.map { habitEntity -> habitEntityToHabit.map(habitEntity) } }
چشم این مپر هم اصلاح شد

2023-12-08 14:38 UTC, mohammadjelodar13657 commented on app/src/main/java/com/quadroidev/medic/data/di/module/DataModule.kt
> +    fun provideReminderRepository(reminderLocalDataSource: ReminderLocalDataSource): ReminderRepository =
اصلاح شد

2023-12-09 06:48 UTC, SinaPakdel approved these changes

2023-12-09 06:52 UTC, SinaPakdel reviewed
اقای جلودار عزیز این آیکن ها رو به صورت (ic_***name***)
قرار بده

2023-12-12 19:23 UTC, closed without merging