Local/[feature] add user to db
QuadroiDev/Medic pull request #5
Opened 2023-11-25 20:46 UTC by QuadroiDev

2023-11-26 17:50 UTC, pooriadarvishi commented
سینا لطفا کامیتای زیاد نزن نهایتا هر تسکو با دوتا کامیت جمع کن ریویو کردن خیلی داستانه اینجور 
هر کامیت که میزنی هدف کلی تسک رو نشون بده تا دونه دونه پیاده سازیای کوچیکو

2023-11-26 17:51 UTC, pooriadarvishi commented
<img width="754" alt="Screenshot 2023-11-26 at 9 21 23 PM" src="https://github.com/QuadroiDev/Medic/assets/113296216/e030a1c4-dc89-48c6-8e8f-cdbfe867f1dd">
اینتر زدی کامیت کردی ؟!

2023-11-26 17:56 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/core/components/interactores/UseCase.kt
> +        Log.e("TAG", "invoke: $e", )
این لاگ رو بردار اگه میخوای استفاده کنی ازش داخل یه error handler هندلش کن

2023-11-26 18:02 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/core/model/User.kt
> +data class User(val name: String)
اینو لطفا کاملش کن دستت درد نکنه

2023-11-26 18:05 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/data/di/module/DataModule.kt
> +object DataModule {
<img width="762" alt="Screenshot 2023-11-26 at 9 34 49 PM" src="https://github.com/QuadroiDev/Medic/assets/113296216/c73ed452-b768-4a45-913a-1141796d7449">
اینطوری خوانا ترو راحت تر نبود؟

2023-11-26 18:05 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/data/di/module/DataModule.kt
> +object DataModule {
برای هر جفتشون

2023-11-26 18:20 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/core/components/base/BaseFragment.kt
>  abstract class BaseFragment<VB : ViewBinding, VM : ViewModel>(
bindingInflater سینا برای این پراپرتی یه لامبدا میگیری که بهش سه تا آرگیومنت پاس میدی لطفا اسم براشون بزار که خوانا تر بشه مخصوصا اون boolean چون نفهمیدم چی هست چه کاربردی داره

2023-11-26 18:26 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
>  class LoginFragment : BaseFragment<FragmentLoginBinding, LoginViewModel>(
این تیکه کدی که ویو باندینگو با ویو مدل رو اینیشیال کردی خیلی خفن بود دمت گرم

2023-11-26 18:32 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
> +            viewModel.createUser(binding.tvUserName.text.toString())
(اختیاری*) فک کنم به جای create user بشه اسم بهتریی پیدا کرد چون هم امکان داره sign up کنه هم login یه اسم بین این دو باشه و تو یوز کیس ها هم عوض شه

2023-11-26 18:34 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginViewModel.kt
> +            createUserUseCase.invoke(CreateUserUseCase.Params(User(username)))
فک کنم اینو دو خط کنی بهتر باشه خط بالا یوزر ساخته شه بعد بدیش به اینجا

2023-11-26 18:37 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/core/model/User.kt
> +data class User(val name: String)
یا چون تو ورودی شماره مبایل میگیریم یه نام بزار که دیفالتش همون goast هست و یدونه شماره 
یه یوزر دیگه بساز که این دوتارو داره ولی برای نام حالت دیفالت نداره و بقیه پراپرتی هایی که نیازه مثل سن و جنسیت رو هم داره (برای زمانی که کاربر از تنظیمات اطلاعاتش رو کامل میکنه)

2023-11-26 18:38 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
> +    private fun observeLoginEvents() {
بهتر نیست این فانکشن رو بیاری داخل basefragment ؟ (ازونجایی که همه فرگمنت هامون یه ایونتی داخلشون اتفاق میوفته)

2023-11-26 18:39 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
> +    private fun observeLoginEvents() {
فعالت navigate کردن رو بیار داخل این که اگر لاگین ساکسز بود نویگیت کنیم

2023-11-26 18:55 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/data/di/module/DataModule.kt
> +object DataModule {
البته برا ریپازیتوری چون اینتر فیس بالا سرشه باید یکم سرچ کنی ببینی راهی هست یا نه

2023-11-26 18:56 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
>              findNavController().navigate(LoginFragmentDirections.actionLoginFragmentToMainFragment())
استکش هم اوکی کن کاربر بک زد برنگرده تو این صفحه

2023-11-26 18:57 UTC, pooriadarvishi commented
سینا حالت با کد تایید وارد شدن هم پیاده سازی کن کد احرازشم بزار ۱۲۳۴

2023-11-26 18:59 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
> +    private fun observeLoginEvents() {
نویگیت رو بزار بعد تست چون تست رو نشون نمیده قبلش

2023-11-26 19:04 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/core/local/models/UserEntity.kt
> +    @ColumnInfo("gender") val gender: Gender? = Gender.OTHER,
<img width="898" alt="Screenshot 2023-11-26 at 10 33 42 PM" src="https://github.com/QuadroiDev/Medic/assets/113296216/c3204102-b540-407c-9070-68c24fe54756">
اینم برای اون قسمت که دیفالت OTHER ندی بهش

2023-11-26 19:12 UTC, pooriadarvishi commented
برای ورود هم لطفا از کاربر شماره تلفن بگیر تا username مرحله بعدش میشه کد احراز اگه انلاین بخواد وارد بشه بعد مرحله بعدیش میشه اسمش(نام کاربری نه)

2023-11-26 19:13 UTC, pooriadarvishi requested changes
خدا قوت خسته نباشی
این مواردی که گفتمو انجام بده لطفا اگه جایی رو قبول نداشتی بنویس زیرش اخرشم که همش تکمیل شد یه پیام بهم بده بیام کامنارو بخونم دونه دونه چک کنم

2023-11-26 19:13 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/core/components/model/EntityModelAdapter.kt
> +class EntityModelAdapter<DataEntity, Model>(
سینا این خیلی خفنه ولی احساس میکنم میشه بهترش کرد 
<img width="238" alt="Screenshot 2023-11-26 at 10 37 05 PM" src="https://github.com/QuadroiDev/Medic/assets/113296216/14ea4793-5352-45a5-a50b-87fe21280511">
این برای مپرش 
<img width="698" alt="Screenshot 2023-11-26 at 10 37 59 PM" src="https://github.com/QuadroiDev/Medic/assets/113296216/7422d37d-ed23-4af8-9396-9d72532431d6">
اینم برای حالت لیستش 
حالا چک کن بازم ببین کدوم بهتره اگه موافق نبودی یه تایمی بگو در موردش گفت و گو کنیم

2023-11-27 16:22 UTC, QuadroiDev commented
> <img alt="Screenshot 2023-11-26 at 9 21 23 PM" width="754" src="https://private-user-images.githubusercontent.com/113296216/285670361-e030a1c4-dc89-48c6-8e8f-cdbfe867f1dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMDIzNzIsIm5iZiI6MTcwMTEwMjA3MiwicGF0aCI6Ii8xMTMyOTYyMTYvMjg1NjcwMzYxLWUwMzBhMWM0LWRjODktNDhjNi04ZThmLWNkYmZlODY3ZjFkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyN1QxNjIxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDY4ODBmY2M4NTc0ZTY3OWY5N2Y0YWUyOWM0N2Y2ZTU4NWU0NDhhOTkzNzg2Mjc1MWY2MjRmOGM5NzViZjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KPlyFSuT3Q2NdhRx8AJ3LIhq1efvEITWbIq2NwDVSFI"> اینتر زدی کامیت کردی ؟!

نه این و تو زده بوی  و من برش داشتم

2023-11-27 16:37 UTC, SinaPakdel commented on app/src/main/java/com/quadroidev/medic/core/components/interactores/UseCase.kt
> +        Log.e("TAG", "invoke: $e", )
نمیدونم دقیقا منظورت چیه

2023-11-27 16:39 UTC, SinaPakdel commented on app/src/main/java/com/quadroidev/medic/core/model/User.kt
> +data class User(val name: String)
ببین پوریا ما فعلا هیچ ui نداریم و نمیدونم قراره چی بگیریم

اونم مهم نیست بر اساس نیاز میشه هر چی گذاشت ولی الان نیازی نداریم من برای اینکه راه و روش ساختش رو پیاده کنم نوشتمش وگرنه در حال حاضر و تو این استیج ما بیزینیسمون اینه که بدون لاگین وارد شه

2023-11-27 16:40 UTC, SinaPakdel commented on app/src/main/java/com/quadroidev/medic/data/di/module/DataModule.kt
> +object DataModule {
چرا باید این کلاس singletone بشه!

2023-11-27 16:44 UTC, SinaPakdel commented on app/src/main/java/com/quadroidev/medic/core/components/base/BaseFragment.kt
>  abstract class BaseFragment<VB : ViewBinding, VM : ViewModel>(
اون برای inflate کردن ه ویو و همون اتچ شدنه که گفتم نشه

2023-11-27 16:44 UTC, SinaPakdel commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
>  class LoginFragment : BaseFragment<FragmentLoginBinding, LoginViewModel>(
چاکریم داوشش

2023-11-27 16:46 UTC, SinaPakdel commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
> +            viewModel.createUser(binding.tvUserName.text.toString())
اره اسم بهتر میشه موافقم
درستش اینه که بگیم یوزر کیک کرد

2023-11-27 16:47 UTC, SinaPakdel commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
> +    private fun observeLoginEvents() {
این و یادم ه استاد میگفت نکن
منم قبلا اینکار و کردم 
میگفت ممکنه یه جایی نیاز نداشته باشی بهش بهتره نزاریش

2023-11-27 16:47 UTC, SinaPakdel commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
>              findNavController().navigate(LoginFragmentDirections.actionLoginFragmentToMainFragment())
حله

2023-11-27 16:48 UTC, SinaPakdel commented
> سینا حالت با کد تایید وارد شدن هم پیاده سازی کن کد احرازشم بزار ۱۲۳۴

پوریا این و باید بشینیم فک کنیم نمیشه همینجوری زد و رفت دوباره کاریه

2023-11-27 16:54 UTC, SinaPakdel commented on app/src/main/java/com/quadroidev/medic/core/components/model/EntityModelAdapter.kt
> +class EntityModelAdapter<DataEntity, Model>(
من نمیدونم این چه مدلی میشه

ولی اگه میگی تمیز تر میشه بیا از همین استفاده کنیم فقط باید صحبت کنیم که چجوری ازش استفاده کنیم

2023-11-27 21:47 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/data/di/module/DataModule.kt
> +object DataModule {
سینگلتون نیاز نیست من فقط سمپل گزاشتم

2023-11-27 21:49 UTC, pooriadarvishi commented on app/src/main/java/com/quadroidev/medic/presentation/features/login/LoginFragment.kt
> +    private fun observeLoginEvents() {
اخه الان تست رو نشون نمیده مگه اینکه از صفحه بعدی بک بزنیم عملا تست یا هر عملیاتی داخل ایونت بی فایدست

2023-11-28 05:33 UTC, justcena commented on app/src/main/java/com/quadroidev/medic/data/di/module/DataModule.kt
> +object DataModule {
تو میگی ماژول نکنیم منظورت رو نمی‌فهمم

2023-11-28 20:59 UTC, pooriadarvishi approved these changes

2023-11-28 21:01 UTC, merged